- hosts: windows
  gather_facts: yes
  tasks:
    - name: Verify account
      ansible.windows.win_ping:
      vars:
        ansible_user: "{{ account.username }}"
        ansible_password: "{{ account.secret }}"
