- hosts: demo
  gather_facts: no
  tasks:
    - name: Test privileged account
      ansible.windows.win_ping:

#    - name: Print variables
#      debug:
#        msg: "Username: {{ account.username }}, Password: {{ account.secret }}"

    - name: Change password
      ansible.windows.win_user:
        name: "{{ account.username }}"
        password: "{{ account.secret }}"
        update_password: always
      when: account.secret_type == "password"

    - name: Refresh connection
      ansible.builtin.meta: reset_connection

    - name: Verify password
      ansible.windows.win_ping:
      vars:
        ansible_user: "{{ account.username }}"
        ansible_password: "{{ account.secret }}"
      when: account.secret_type == "password"
