# SECURITY WARNING: keep the secret key used in production secret!
# 加密密钥 生产环境中请修改为随机字符串，请勿外泄, 可使用命令生成
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
SECRET_KEY: Kj8mN2pQ9rS4tU7vW1xY3zA5bC6dE8fG0hI2jK4lM6nO8pQ0rS2tU4vW6xY8zA0bC2dE4fG6hI8jK0lM2nO4pQ6rS8tU0vW2xY4zA6bC8dE0fG2hI4jK6lM8nO0pQ2rS4tU6vW8xY0zA2bC4dE6fG8hI0jK2lM4nO6pQ8rS0tU2vW4xY6zA8bC0dE2fG4hI6jK8lM0nO2pQ4rS6tU8vW0xY2zA4bC6dE8fG0hI2jK4lM6nO8pQ0rS2tU4vW6xY8zA0bC2dE4fG6hI8jK0lM2nO4pQ6rS8tU0vW2xY4zA6bC8dE0fG2hI4jK6lM8nO0pQ2rS4tU6vW8xY0zA2bC4dE6fG8hI0jK2lM4nO6pQ8rS0tU2vW4xY6z

# SECURITY WARNING: keep the bootstrap token used in production secret!
# 预共享Token coco和guacamole用来注册服务账号，不在使用原来的注册接受机制
BOOTSTRAP_TOKEN: pfTwIXJT6Cu-dCya1VEw8NC0Ui8_IHJS

# Development env open this, when error occur display the full process track, Production disable it
# DEBUG 模式 开启DEBUG后遇到错误时可以看到更多日志
DEBUG: true

# DEBUG, INFO, WARNING, ERROR, CRITICAL can set. See https://docs.djangoproject.com/en/1.10/topics/logging/
# 日志级别
LOG_LEVEL: DEBUG
# LOG_DIR:

# Session expiration setting, Default 1 hour, Also set expired on on browser close
# 浏览器Session过期时间，默认 1 小时, 也可以设置浏览器关闭则过期
# SESSION_COOKIE_AGE: 3600
# SESSION_EXPIRE_AT_BROWSER_CLOSE: false

# 系统语言设置
LANGUAGE_CODE: 'zh-hans'

# Database setting, Support sqlite3, mysql, postgres ....
# 数据库设置
# See https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# SQLite setting:
# 使用单文件sqlite数据库
# DB_ENGINE: sqlite3
# DB_NAME:
# MySQL or postgres setting like:
# 使用 PostgreSQL 作为数据库
DB_ENGINE: postgresql
DB_HOST: 192.168.7.113
DB_PORT: 25432
DB_USER: postgres
DB_PASSWORD: postgres123
DB_NAME: postgres

# When Django start it will bind this host and port
# ./manage.py runserver 127.0.0.1:8080
# 运行时绑定端口
HTTP_BIND_HOST: 0.0.0.0
HTTP_LISTEN_PORT: 8080
WS_LISTEN_PORT: 8070

# Use Redis as broker for celery and web socket
# Redis配置
REDIS_HOST: 192.168.7.113
REDIS_PORT: 16379
# REDIS_PASSWORD:
# REDIS_DB_CELERY: 3
# REDIS_DB_CACHE: 4

DOMAINS: "192.168.6.224:9528,docker build --platform linux/amd64 -t   jumpserver/core:from-4.10.7 .192.168.111.138:9528"

# 关闭远程应用的客户端RDP方式 只支持web方式
TERMINAL_RAZOR_ENABLED: false


#认证配置
AUTH_RADIUS: true    # 启用 RADIUS 认证


# LDAP/AD settings
# LDAP 搜索分页数量
# AUTH_LDAP_SEARCH_PAGED_SIZE: 1000
#
# 定时同步用户
# 启用 / 禁用
# AUTH_LDAP_SYNC_IS_PERIODIC: True
# 同步间隔 (单位: 时) (优先）
# AUTH_LDAP_SYNC_INTERVAL: 12
# Crontab 表达式
# AUTH_LDAP_SYNC_CRONTAB: * 6 * * *
#
# LDAP 用户登录时仅允许在用户列表中的用户执行 LDAP Server 认证
# AUTH_LDAP_USER_LOGIN_ONLY_IN_USERS: False
#
# LDAP 认证时如果日志中出现以下信息将参数设置为 0 (详情参见：https://www.python-ldap.org/en/latest/faq.html)
# In order to perform this operation a successful bind must be completed on the connection
# AUTH_LDAP_OPTIONS_OPT_REFERRALS: -1

# OTP settings
# OTP/MFA 配置
# OTP_VALID_WINDOW: 0
# OTP_ISSUER_NAME: JumpServer

# 启用定时任务
# PERIOD_TASK_ENABLED: True
#

# 是否开启 Luna 水印
# SECURITY_WATERMARK_ENABLED: False

# 浏览器关闭页面后，会话过期
# SESSION_EXPIRE_AT_BROWSER_CLOSE: False

# 每次 api 请求，session 续期
# SESSION_SAVE_EVERY_REQUEST: True

# 仅允许用户从来源处登录
# ONLY_ALLOW_AUTH_FROM_SOURCE: False

# 仅允许已存在的用户登录，不允许第三方认证后，自动创建用户
# ONLY_ALLOW_EXIST_USER_AUTH: False

# 开启人脸识别 XPACK 功能
#FACE_RECOGNITION_ENABLED: true
#FACE_RECOGNITION_DISTANCE_THRESHOLD': 0.35
#FACE_RECOGNITION_COSINE_THRESHOLD': 0.95

# RADIUS 认证配置
RADIUS_SERVER: 'localhost'
RADIUS_PORT: 1812
RADIUS_SECRET: 'testing123'
RADIUS_ATTRIBUTES: {}
RADIUS_ENCRYPT_PASSWORD: True
OTP_IN_RADIUS: False
RADIUS_ORG_IDS: [1]
