- hosts: mysql
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python
    jms_account:
      username: root
      secret: redhat
    jms_asset:
      address: 127.0.0.1
      port: 3306
    account:
      username: web1
      secret: jumpserver

  tasks:
    - name: Test MySQL connection
      community.mysql.mysql_info:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        filter: version
      register: db_info

    - name: MySQL version
      debug:
        var: db_info.version.full

    - name: Change MySQL password
      community.mysql.mysql_user:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        name: "{{ account.username }}"
        password: "{{ account.secret }}"
        host: "%"
      when: db_info is succeeded

    - name: Verify password
      community.mysql.mysql_info:
        login_user: "{{ account.username }}"
        login_password: "{{ account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        filter: version
