---

- hosts: all
  vars:
    applet_name: chrome

  tasks:
    - name: Install applet
      ansible.windows.win_shell:
        "tinkerd install --name {{ applet_name }}"
      when: applet_name != 'all'
