# Generated by Django 4.1.13 on 2025-09-13 09:17

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0009_session_replay_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='highgo_port',
            field=common.db.fields.PortField(default=58660, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='HighGo port'),
        ),
    ]
