# Generated by Django 4.1.13 on 2025-10-17 10:00

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_endpoint_highgo_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='kingbase_port',
            field=common.db.fields.PortField(
                default=54322, 
                validators=[
                    django.core.validators.MinValueValidator(0), 
                    django.core.validators.MaxValueValidator(65535)
                ], 
                verbose_name='Kingbase port'
            ),
        ),
    ]

