- hosts: mongodb
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python

  tasks:
    - name: Get info
      mongodb_ping:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        login_database: "{{ jms_asset.specific.db_name }}"
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info:
          version: "{{ db_info.server_version }}"

    - debug:
        var: info
