# Generated by Django 4.1.13 on 2025-09-24 03:30

import common.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_user_wechat_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usb_key_certificate_cn',
            field=models.CharField(blank=True, help_text='USB Key证书CN项', max_length=256, null=True, verbose_name='USB Key Certificate CN'),
        ),
        migrations.AddField(
            model_name='user',
            name='usb_key_public_key',
            field=common.db.fields.EncryptTextField(blank=True, help_text='USB Key公钥，用于USB Key OTP认证', null=True, verbose_name='USB Key Public Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='usb_key_serial_number',
            field=models.CharField(blank=True, help_text='USB Key序列号', max_length=128, null=True, verbose_name='USB Key Serial Number'),
        ),
    ]
