# Generated by Django 4.1.13 on 2025-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_usb_key_certificate_cn_user_usb_key_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usb_key_enabled',
            field=models.BooleanField(default=False, verbose_name='USB Key Enabled'),
        ),
    ]
