services:
  core:
    image: ${REGISTRY:-docker.io}/jumpserver:x86-latest 
#    image: ${REGISTRY:-docker.io}/jms_core:v4.1.1-ce 
    container_name: jms_core
    hostname: jms_core
    ulimits:
      core: 0
    restart: always
    command: start web
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/certs:/opt/jumpserver/data/certs
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - /dev/shm/:/dev/shm/
    devices:
      - /dev/tsr-dev0:/dev/tsr-dev0     
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - "8080:8080"
    networks:
      - net
