- name: Check connection
  ping:

- name: Change password
  user:
    name: "{{ item }}"
    password: "{{ password.value | password_hash('sha512') }}"
    update_password: always
  with_items: "{{ usernames }}"
  when: "{{ password.value }}"

- name: Change public key
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', id_rsa.pub) }}"
    state: present
    exclusive: "{{ public_key.exclusive }}"
  with_items: "{{ usernames }}"
  when: "{{ public_key.value and key_strategy != 'set_jms' }}"

- name: Change public key
  lineinfile:
    user: "{{ item }}"
    dest: /home/{{ item }}/.ssh/authorized_keys regexp='.*{{ public_key.value }}$
    state: absent
  with_items: "{{ usernames }}"
  when: "{{ public_key.value and key_strategy == 'set_jms' }}"

- name: Verify user
  ping:
  vars:
    ansible_user: "{{ item }}"
    ansible_pass: "{{ password.value }}"
    ansible_ssh_private_key_file: "{{ private_key_file }}"
    ansible_connection: "{{ connection_type | default('ssh') }}"
  with_items: "{{ usernames }}"
