# Generated by Django 4.1.13 on 2025-09-24 03:08

import common.db.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_alter_accesskey_secret_alter_temptoken_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='USBKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='USB Key名称，用于标识不同的USB Key', max_length=128, verbose_name='USB Key Name')),
                ('public_key', common.db.fields.EncryptTextField(help_text='USB Key的公钥，用于验证签名', verbose_name='Public Key')),
                ('serial_number', models.CharField(help_text='USB Key的序列号', max_length=128, verbose_name='Serial Number')),
                ('certificate_cn', models.CharField(help_text='证书的CN项', max_length=256, verbose_name='Certificate CN')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此USB Key', verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('date_last_used', models.DateTimeField(blank=True, help_text='最后使用时间', null=True, verbose_name='Date Last Used')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usb_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'USB Key',
                'verbose_name_plural': 'USB Keys',
                'unique_together': {('user', 'serial_number')},
            },
        ),
    ]
