# Generated by Django 4.1.13 on 2025-10-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usbkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USBKey',
        ),
    ]
