on:
  issue_comment:
    types: [created]

name: Add issues workflow labels

jobs:
  add-label-if-is-author:
    runs-on: ubuntu-latest
    if: (github.event.issue.user.id == github.event.comment.user.id) && !github.event.issue.pull_request && (github.event.issue.state == 'open')
    steps:
      - name: Add require handle label
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'add-labels'
          labels: '状态:待处理'

      - name: Remove require reply label
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'remove-labels'
          labels: '状态:待反馈'

  add-label-if-is-developers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Project Developers
        uses: octokit/request-action@v2.x
        id: developers
        with:
          route: GET /repos/${{ github.repository }}/collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process developers data
        # 将 developers 中的数据转化为 login 字段的列表并输出
        id: developer_names
        run: echo "::set-output name=data::$(echo '${{ steps.developers.outputs.data }}' | jq '{login}' | jq 'keys'"

      - run: "echo developers: '${{ steps.developers.outputs.data }}'"
      - run: "echo developer names: '${{ steps.developer_names.outputs.data }}'"
      - run: "echo comment user: '${{ github.event.comment.user.login }}'"
      - run: "echo contains? : '${{ contains(steps.developer_names.outputs.data, github.event.comment.user.login) }}'"

      - name: Add require replay label
        if: contains(steps.developer_names.outputs.data, github.event.comment.user.login)
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'add-labels'
          labels: '状态:待反馈'

      - name: Remove require handle label
        if: contains(steps.developer_names.outputs.data, github.event.comment.user.login)
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'remove-labels'
          labels: '状态:待处理'
