name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  issue-close-require:
    runs-on: ubuntu-latest
    steps:
      - name: need reproduce
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issues'
          labels: '状态:待反馈'
          inactive-day: 30
          body: |
            由于该 issue 被标记为 状态:待反馈，30 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

      - name: needs more info
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issues'
          labels: 'needs-more-info'
          inactive-day: 30
          body: |
            Since the issue was labeled with `needs-more-info`, but no response in 30 days. This issue will be closed. If you have any questions, you can comment and reply.
